apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: arcus-ingress
  namespace: arcus
spec:
  rules:
    - host: arcus.rdlts.com
      http:
        paths:
          - path: /arucs
            pathType: Prefix
            backend:
              service:
                name: arcus-gateway
                port:
                  number: 8080