apiVersion: v1
kind: Service
metadata:
  name: arcus-mysql-8
  namespace: arcus
spec:
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: 3306
      nodePort: 30001  # 你选择的固定端口
  selector:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: arcus-mysql-8
  type: NodePort
