spring:
  application:
    name: arcus-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: jdk-features-route
              uri: http://jdk-features:8080
              predicates:
                - Path=/jdk-features/**
              filters:
                - StripPrefix=1
    nacos:
      discovery:
        server-addr: nacos-headless:8848
        namespace: public

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: INFO