spring:
  config:
    import: "nacos:arcus-adv-webflux-local"
  cloud:
    nacos:
      config:
        server-addr: http://localhost:8848
        namespace: arcus-local
        group: DEFAULT_GROUP
        file-extension: yml


