server:
  port: 9000

spring:
  application:
    name: arcus-adv-webflux
  webflux:
    base-path: /arcus-adv-webflux # webflux base path

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  show-actuator: false