# ================= Deployment =================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jdk-features
  namespace: arcus
  labels:
    app: jdk-features
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jdk-features
  template:
    metadata:
      labels:
        app: jdk-features
      annotations:
        last-updated: "2025-06-16T00:00:00Z"  # 更新为当前时间
    spec:
      containers:
        - name: jdk-features
          image: jdk-features:lts
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          imagePullPolicy: Never # 使用本地镜像

---
# ================= Service =================
apiVersion: v1
kind: Service
metadata:
  name: jdk-features
  namespace: arcus
  labels:
    app: jdk-features
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: jdk-features

---
