# Nacos Standalone Deployment for Arcus
---
apiVersion: v1
kind: Service
metadata:
  name: nacos-headless
  namespace: arcus
  labels:
    app: nacos-headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 8848
      name: server
      targetPort: 8848
#      protocol: TCP
#      nodePort: 30848  # Exposed port for Nacos console and API
    - port: 9848
      name: client-rpc
      targetPort: 9848
#      protocol: TCP
#      nodePort: 30948  # Exposed port for client RPC
    - port: 9849
      name: raft-rpc
      targetPort: 9849
    - port: 7848
      name: old-raft-rpc
      targetPort: 7848
  selector:
    app: nacos
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-cm
  namespace: arcus
data:
  mysql.host: "host.docker.internal"
  mysql.db.name: "arcus-nacos"
  mysql.port: "3308"
  mysql.user: "arcus"
  mysql.password: "123456"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nacos
  namespace: arcus
spec:
  serviceName: nacos-headless
  replicas: 1
  selector:
    matchLabels:
      app: nacos
  template:
    metadata:
      labels:
        app: nacos
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      containers:
        - name: nacos
          imagePullPolicy: IfNotPresent
          image: nacos/nacos-server:latest
          resources:
            requests:
              memory: "1Gi"
              cpu: "250m"
          ports:
            - containerPort: 8848
              name: client
            - containerPort: 9848
              name: client-rpc
            - containerPort: 9849
              name: raft-rpc
            - containerPort: 7848
              name: old-raft-rpc
          env:
            - name: MODE
              value: "standalone"
            - name: MYSQL_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.host
            - name: MYSQL_SERVICE_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.db.name
            - name: MYSQL_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.port
            - name: MYSQL_SERVICE_USER
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.user
            - name: MYSQL_SERVICE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.password
            - name: SPRING_DATASOURCE_PLATFORM
              value: "mysql"
            - name: NACOS_SERVER_PORT
              value: "8848"
            - name: NACOS_APPLICATION_PORT
              value: "8848"
            - name: PREFER_HOST_MODE
              value: "hostname"
            - name: NACOS_CONTEXT_PATH
              value: "/"
#            - name: NACOS_SERVERS
#              value: "nacos-0.nacos-headless.default.svc.cluster.local:8848 nacos-1.nacos-headless.default.svc.cluster.local:8848 nacos-2.nacos-headless.default.svc.cluster.local:8848"
#            - name: NACOS_AUTH_ENABLE
#              value: "false"
#            - name: NACOS_AUTH_ADMIN_ENABLE
#              value: "false"
#            - name: NACOS_AUTH_CONSOLE_ENABLE
#              value: "false"
            - name: NACOS_AUTH_TOKEN
              value: "GVKb9w09PjbsfDA9clZEfN12Ye2IupDVes9lM/Kfj+A="
            - name: NACOS_AUTH_IDENTITY_KEY
              value: "arcus"  # 默认值
            - name: NACOS_AUTH_IDENTITY_VALUE
              value: "123456"  # 默认值

